# Generated by Django 4.2.7 on 2024-04-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_artisticgenre_location_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='invitation',
        ),
        migrations.RemoveField(
            model_name='location',
            name='party_date',
        ),
        migrations.RemoveField(
            model_name='location',
            name='party_time',
        ),
        migrations.AddField(
            model_name='artisticgenre',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
