[tool.poetry]
name = "events-django-htmx"
version = "0.1.0"
description = ""
authors = ["anne"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "4.2.7"
pytest-django = "4.7.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
